import About from '@/components/about/about'
import React from 'react'

export const metadata = {
  title: "About Us",
  description: "This 'About Us' page is generated by a web application created using create next app. Here, you can learn about our company's history, values, team, and our commitment to providing exceptional products/services.",
};
const AboutPage = () => {
  return (
    <><About/></>
  )
}

export default AboutPage